---
title: "Data Processing"
author: "Arfa Aijazi"
date: "October 2023"
output:
  html_document:
    df_print: paged
---

This script processes the merged RECS data in preparation for machine learning

### Setup
Load libraries
```{r echo=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
library(caret)
library(knitr)
library(pROC)

options(es.use_symbols = TRUE)
```

Import data
```{r}
recs_subset <- read.csv("../data/recs_subset.csv", stringsAsFactors = TRUE)

x <- recs_subset %>% select(-TEMPMA)
y <- recs_subset$TEMPMA
```

### Data Pre-processing 
Creating dummy variables
```{r}
dummies_model <- dummyVars(TEMPMA ~ ., sep = ".", data = recs_subset)

# Create the dummy variables using predict. The y variable (TEMPMA) will not be present in recs_dummy_mat
recs_dummy_mat <- predict(dummies_model, newdata = recs_subset)

# Convert to dataframe
recs_dummy <- data.frame(recs_dummy_mat)
recs_dummy$TEMPMA <- y
```

Zero- and Near Zero-Variance Predictors

```{r}
# nzv <- nearZeroVar(recs_dummy, saveMetrics = TRUE)
nzv <- nearZeroVar(recs_dummy) # with default threshold for nzv
recs_nzv <- recs_dummy[,-nzv]
recs_nzv$TEMPMA <- y # add TEMPMA back
```

Drops 31 features

Correlated predictors
```{r}
descrCor <-  cor(recs_nzv)
highlyCorDescr <- findCorrelation(descrCor, cutoff = .75)
recs_cor <- recs_nzv[,-highlyCorDescr]
```

Drops 11 features

Linear dependencies
```{r}
comboInfo <- findLinearCombos(recs_cor) # No remaining features are linearly correlated
recs_lin <- recs_cor
```

Drops 0 features

Scale data to the interval between zero and one
```{r}
preProcValues <- preProcess(recs_lin, method = "range")
recs_range <- predict(preProcValues, recs_lin)
```

### Export
```{r}
write_csv(recs_range, "../data/recs_range.csv")
```
