---
title: "Results Analysis"
author: "Arfa Aijazi"
date: "2023-11-26"
output: html_document
---
This script analyzes the machine learning model results

### Setup
```{r}
library(tidyverse)
library(scales)
library(ggpubr)
```

Custom plot theme
```{r message=FALSE, warning=FALSE, include=FALSE}
theme_custom = function() {
  theme_minimal() %+replace%
    theme(legend.position = "top") +
    theme(panel.grid = element_blank()) +
    theme(strip.background = element_blank()) +
    theme(panel.border = element_blank()) +
    theme(panel.background = element_blank()) +
    #theme(legend.title = element_blank()) +
    theme(axis.title = element_blank()) +
    theme(text = element_text(size = 7, colour = "#000000"))
}
```

Color palette
```{r}
## custom colors
my_pal3 <- rcartocolor::carto_pal(n = 3, name = "Pastel")
my_pal5 <- rcartocolor::carto_pal(n = 5, name = "Pastel")
my_pal8 <- rcartocolor::carto_pal(n = 9, name = "Pastel")
```

### Load data
```{r}
results_file <- "../data/results_compiled_20231125.csv"

results_compiled <- read_csv(results_file) %>%
  replace(is.na(.), 0) %>%
  mutate(imbalance = factor(imbalance, levels = c("none", "weighted", "up", "smote", "rose"))) %>%
  mutate(mLMethod = factor(mLMethod, levels = c("glm", "earth", "pda", "multinom", "treebag", "gbm", "ranger", "nnet"))) %>%
  mutate(input_features = factor(input_features, levels = c("Baseline", "All"))) %>%
  arrange(-BalancedAccuracy) %>%
  mutate(Number = row_number()) %>%
  mutate(time.elapsed = time.end - time.start) %>%
  rename(mlMethod = mLMethod) %>%
  mutate(mlType = case_when(mlMethod == "glm" ~ "Regression",
                            mlMethod == "earth" ~ "Regression",
                            mlMethod == "pda" ~ "Dimensionality reduction",
                            mlMethod == "multinom" ~ "Dimensionality reduction",
                            mlMethod == "treebag" ~ "Decision tree",
                            mlMethod == "gbm" ~ "Ensemble",
                            mlMethod == "ranger" ~ "Ensemble",
                            mlMethod == "nnet" ~ "Artificial neural network")) %>%
  mutate(mlMethod.label = case_when(mlMethod == "glm" ~ "Genarlized linear model",
                            mlMethod == "earth" ~ "Multivariate adaptive regression spline",
                            mlMethod == "pda" ~ "Penalized discriminant analysis",
                            mlMethod == "multinom" ~ "Penalized multinomal regression",
                            mlMethod == "treebag" ~ "Classification and regression trees",
                            mlMethod == "gbm" ~ "Gradient boosting machine",
                            mlMethod == "ranger" ~ "Random forest",
                            mlMethod == "nnet" ~ "Neural network")) %>%
  mutate(imbalance.label = case_when(imbalance == "none" ~ "None",
                                     imbalance == "weighted" ~ "Class weights",
                                     imbalance == "up" ~ "Up-sample",
                                     imbalance == "smote" ~ "SMOTE",
                                     imbalance == "rose" ~ "ROSE"))
```
```{r}
results_bootstrapped <- results_compiled %>%
  select(-starts_with("time."), -Number) %>%
  pivot_longer(cols = Precision:BalancedAccuracy, names_to = "metric", values_to = "value") %>%
  group_by(input_features, imbalance, mlMethod, metric) %>%
  summarise(mean = mean(value), sd = sd(value), n = n()) %>%
  pivot_wider(names_from = metric, values_from = c(mean, sd)) %>%
  arrange(-mean_BalancedAccuracy) %>%
  ungroup() %>%
  mutate(Number = row_number()) 
```


Plot by data input features
```{r}
plot_BalancedAccuracy_input <- ggplot(results_bootstrapped, aes(x = Number, y = mean_BalancedAccuracy, fill = input_features)) +
  scale_fill_manual(values = rev(my_pal3)) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = mean_BalancedAccuracy-(2*sd_BalancedAccuracy), ymax = mean_BalancedAccuracy+(2*sd_BalancedAccuracy)), position = position_dodge(width = 0.8), width = 0.2, colour = "#000000", linewidth = 0.2) +
  geom_hline(yintercept = 0.5, linetype = "dashed", linewidth = 0.3, colour = "#b2182b") +
  scale_x_continuous(breaks = seq(0, 80, by = 10), expand = c(0,0)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.2)) +
  coord_cartesian(xlim = c(0,80.5), ylim = c(0,1)) +
  theme_custom() +
  theme(axis.text.x = element_blank()) +
  theme(panel.grid.major.y = element_line(colour = "#f7f7f7")) +
  annotate("rect", xmin = 52.5, xmax = 78.5, ymin = -Inf, ymax = Inf, alpha = 0.1, fill = "#b2182b")

plot_Recall_input <- ggplot(results_bootstrapped, aes(x = Number, y = mean_Recall, fill = input_features)) +
  scale_fill_manual(values = rev(my_pal3)) +
  
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = mean_Recall-(2*sd_Recall), ymax = mean_Recall+(2*sd_Recall)), position = position_dodge(width = 0.8), width = 0.2, colour = "#000000", linewidth = 0.2) +
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.3, colour = "#b2182b") +
  scale_x_continuous(breaks = seq(0, 80, by = 10), expand = c(0,0)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.2)) +
  coord_cartesian(xlim = c(0,80.5), ylim = c(0,1)) +
  theme_custom() +
  theme(axis.text.x = element_blank()) +
  theme(panel.grid.major.y = element_line(colour = "#f7f7f7")) +
  annotate("rect", xmin = 52.5, xmax = 78.5, ymin = -Inf, ymax = Inf, alpha = 0.1, fill = "#b2182b")

plot_Precision_input <- ggplot(results_bootstrapped, aes(x = Number, y = mean_Precision, fill = input_features)) +
  scale_fill_manual(values = rev(my_pal3)) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = mean_Precision-(2*sd_Precision), ymax = mean_Precision+(2*sd_Precision)), position = position_dodge(width = 0.8), width = 0.2, colour = "#000000", linewidth = 0.2) +
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.3, colour = "#b2182b") +
  scale_x_continuous(breaks = seq(0, 80, by = 10), expand = c(0,0)) +
  scale_y_continuous(breaks = seq(0, 0.3, by = 0.1)) +
  coord_cartesian(xlim = c(0,80.5), ylim = c(0,0.3)) +
  theme_custom() +
  theme(axis.text.x = element_text()) +
  theme(axis.title.x = element_text()) +
  xlab("Machine learning models (ranked by balanced accuracy)") +
  theme(panel.grid.major.y = element_line(colour = "#f7f7f7")) +
  annotate("rect", xmin = 52.5, xmax = 78.5, ymin = -Inf, ymax = Inf, alpha = 0.1, fill = "#b2182b")
  
ggarrange(plot_BalancedAccuracy_input, plot_Recall_input, plot_Precision_input, align = "hv", nrow = 3, ncol = 1, common.legend = TRUE)
ggsave("Figure2_byInputFeatures.pdf", units = "in", width = 6, height = 4)
```

```{r}
results_converged <- results_compiled %>%
  filter(BalancedAccuracy != 0.5000000)
```

```{r}
plot_BalancedAccuracy_imbalance_box <- ggplot(results_converged, aes(x = reorder(imbalance.label, BalancedAccuracy), y = BalancedAccuracy, fill = input_features)) +
  scale_fill_manual(values = rev(my_pal3)) +
  geom_boxplot() +
  geom_hline(yintercept = 0.5, linetype = "dashed", linewidth = 0.3, colour = "#b2182b") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.2)) +
  coord_cartesian(ylim = c(0,1)) +
  theme_custom() +
  theme(panel.grid.major.y = element_line(colour = "#f7f7f7")) +
  coord_flip()

plot_BalancedAccuracy_mlType_box <- ggplot(results_converged, aes(x = reorder(mlMethod.label, BalancedAccuracy), y = BalancedAccuracy, fill = input_features)) +
  scale_fill_manual(values = rev(my_pal3)) +
  geom_boxplot() +
  geom_hline(yintercept = 0.5, linetype = "dashed", linewidth = 0.3, colour = "#b2182b") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.2)) +
  coord_cartesian(ylim = c(0,1)) +
  theme_custom() +
  theme(panel.grid.major.y = element_line(colour = "#f7f7f7")) +
  coord_flip()

ggarrange(plot_BalancedAccuracy_imbalance_box, plot_BalancedAccuracy_mlType_box, align = "v", nrow = 2, ncol = 1, common.legend = TRUE)
```

```{r}
plot_Recall_imbalance_box <- ggplot(results_converged, aes(x = imbalance, y = Recall, fill = input_features)) +
  scale_fill_manual(values = rev(my_pal3)) +
  geom_boxplot() +
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.3, colour = "#b2182b") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.2)) +
  coord_cartesian(ylim = c(0,1)) +
  theme_custom() +
  theme(panel.grid.major.y = element_line(colour = "#f7f7f7"))

plot_Recall_mlType_box <- ggplot(results_converged, aes(x = mlType, y = Recall, fill = input_features)) +
  scale_fill_manual(values = rev(my_pal3)) +
  geom_boxplot() +
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 0.3, colour = "#b2182b") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.2)) +
  coord_cartesian(ylim = c(0,1)) +
  theme_custom() +
  theme(panel.grid.major.y = element_line(colour = "#f7f7f7"))

ggarrange(plot_Recall_imbalance_box, plot_Recall_mlType_box, align = "hv", nrow = 2, ncol = 1, common.legend = TRUE)
```
